server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dlavender/springcloud-config.git
          search-paths:
            - springcloud-config
          password: dyw19961024
          username: dlavender
          timeout: 200000
      label: master
  rabbitmq:
    host: 192.168.233.134
    port: 5672
    username: admin
    password: 123


eureka:
  client:
    register-with-eureka: true  #将自己注册进EurekaServer
    fetch-registry: true   #获取注册信息
    service-url:
      defaultZone: http://localhost:7001/eureka
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
